main = ".open-next/worker.js"
name = "onefile"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
routes = [
  { pattern = "onefileapp.com", custom_domain = true }
]